------------------------------------------------------------------------------
______ _   _ _____       __                  _                 _            
| ___ \ | | |  _  |     / /                 | |               (_)           
| |_/ / |_| | | | |    / /   ___ _   _ _ __ | |__ ______ _ __  _ _ __   ___ 
|  __/|  _  | | | |   / /   / __| | | | '_ \| '_ \______| '_ \| | '_ \ / _ \
| |   | | | \ \_/ /  / /    \__ \ |_| | |_) | | | |     | |_) | | |_) |  __/
\_|   \_| |_/\___/  /_/     |___/\__, | .__/|_| |_|     | .__/|_| .__/ \___|
                                  __/ | |               | |     | |         
                                 |___/|_|               |_|     |_|         
------------------------------------------------------------------------------

Run Name: $runName

<% if (success){
    out << "## PHO/syph-pipe execution completed successfully! ##"
} else {
    out << """####################################################
## PHO/syph-pipe execution completed unsuccessfully! ##
####################################################
The exit status of the task that caused the workflow execution to fail was: $exitStatus.
The full error message was:

${errorReport}
"""
} %>


The workflow was completed at $dateComplete (duration: $duration)

The command used to launch the workflow was as follows:

  $commandLine



Pipeline Configuration:
-----------------------
<% out << summary.collect{ k,v -> " - $k: $v" }.join("\n") %>

--
PHO/syph-pipe
https://github.com/lilsingh/syph-pipe
